In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/earthquake-database/database.csv

In [4]:
df = pd.read_csv("/kaggle/input/earthquake-database/database.csv")
df.sample(10)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
16548,11/30/2003,21:58:47,-39.2330,-92.0260,Earthquake,10.0,NaN,36.0,5.5,MWC,...,NaN,62.3,NaN,NaN,1.35,USP000CE82,US,US,HRV,Reviewed
11926,05/24/1994,02:05:57,-15.6070,-74.7350,Earthquake,33.7,NaN,NaN,5.6,MW,...,NaN,NaN,NaN,NaN,1.30,USP0006CZV,US,US,HRV,Reviewed
1785,12/12/1970,01:10:42,-20.8120,-177.7940,Earthquake,407.6,NaN,NaN,5.6,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM789091,ISCGEM,ISCGEM,ISCGEM,Automatic
16007,10/10/2002,21:19:59,-1.4780,134.1110,Earthquake,10.0,NaN,198.0,6.0,MWC,...,NaN,NaN,NaN,NaN,0.90,USP000BE7F,US,US,HRV,Reviewed
19700,10/07/2009,23:13:48,-13.0930,166.4970,Earthquake,31.1,2.4,314.0,7.4,MWC,...,NaN,20.2,NaN,NaN,0.96,USP000H2GR,US,US,GCMT,Reviewed
22978,01/31/2016,02:50:06,-2.8659,147.1385,Earthquake,10.0,1.7,NaN,5.7,MWW,...,NaN,24.0,0.848,6.1,1.11,US20004W3K,US,US,US,Reviewed
18234,01/22/2007,04:27:08,-2.5450,136.3410,Earthquake,35.0,NaN,63.0,5.7,MWC,...,NaN,64.2,NaN,NaN,1.04,USP000F38Y,US,US,GCMT,Reviewed
18567,08/11/2007,18:04:53,-22.2640,-179.4930,Earthquake,606.2,NaN,405.0,5.7,MWC,...,NaN,16.6,NaN,NaN,0.81,USP000FJE5,US,US,GCMT,Reviewed
18875,02/21/2008,02:46:18,77.0790,18.5710,Earthquake,12.0,NaN,637.0,6.1,MWC,...,NaN,23.9,NaN,NaN,0.81,USP000FZEU,US,US,GCMT,Reviewed
7290,11/22/1984,17:07:36,-17.7790,-178.0500,Earthquake,645.8,1.5,NaN,6.5,MW,...,NaN,NaN,NaN,NaN,1.00,USP00029AD,US,US,HRV,Reviewed

In [10]:
import datetime as dt

In [11]:
hozir = dt.datetime.now()

In [12]:
type(hozir)

datetime.datetime

In [13]:
print(hozir)

2026-04-30 07:38:54.582956

In [14]:
hozir.hour

7

In [15]:
hozir.minute

38

In [16]:
hozir.weekday()

3

In [17]:
hozir.month

4

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23412 non-null  object
 1   Time                        23412 non-null  object
 2   Latitude                    23412 non-null  float64
 3   Longitude                   23412 non-null  float64
 4   Type                        23412 non-null  object
 5   Depth                       23412 non-null  float64
 6   Depth Error                 4461 non-null   float64
 7   Depth Seismic Stations      7097 non-null   float64
 8   Magnitude                   23412 non-null  float64
 9   Magnitude Type              23409 non-null  object
 10  Magnitude Error             327 non-null    float64
 11  Magnitude Seismic Stations  2564 non-null   float64
 12  Azimuthal Gap               7299 non-null   float64
 13  Horizontal Distance         1604 non-null   float64
 14  Horizontal Error            1156 non-null   float64
 15  Root Mean Square            17352 non-null  float64
 16  ID                          23412 non-null  object
 17  Source                      23412 non-null  object
 18  Location Source             23412 non-null  object
 19  Magnitude Source            23412 non-null  object
 20  Status                      23412 non-null  object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB

In [19]:
df.at[0,'Date']

'01/02/1965'

In [20]:
type(df.at[0,'Date'])

str

In [21]:
pd.to_datetime(df['Date'], format="%m/%d/%Y")

ValueError: time data '1975-02-23T02:58:41.000Z' does not match format '%m/%d/%Y' (match)

In [22]:
df['Date'].str.len().value_counts()

10    23409
24        3
Name: Date, dtype: int64

In [23]:
df[df['Date'].str.len()==24]

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
3378,1975-02-23T02:58:41.000Z,1975-02-23T02:58:41.000Z,8.017,124.075,Earthquake,623.0,NaN,NaN,5.6,MB,...,NaN,NaN,NaN,NaN,NaN,USP0000A09,US,US,US,Reviewed
7512,1985-04-28T02:53:41.530Z,1985-04-28T02:53:41.530Z,-32.998,-71.766,Earthquake,33.0,NaN,NaN,5.6,MW,...,NaN,NaN,NaN,NaN,1.30,USP0002E81,US,US,HRV,Reviewed
20650,2011-03-13T02:23:34.520Z,2011-03-13T02:23:34.520Z,36.344,142.344,Earthquake,10.1,13.9,289.0,5.8,MWC,...,NaN,32.3,NaN,NaN,1.06,USP000HWQP,US,US,GCMT,Reviewed

In [24]:
df.loc[3378, 'Date'] = "02/23/1975"
df.loc[7512, "Date"] = "04/28/1985"
df.loc[20650, "Date"] = "03/13/2011"

In [25]:
df['datetime'] = pd.to_datetime(df['Date'], format="%m/%d/%Y")
df.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-02
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-04
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-05
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-08
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-09

In [26]:
df.at[0,'datetime'].weekday()

5

In [27]:
df['month'] = df['datetime'].dt.month

In [28]:
df['month'].value_counts()

3     2114
8     2014
12    2001
11    1987
9     1985
4     1971
5     1964
10    1952
1     1891
7     1880
2     1829
6     1824
Name: month, dtype: int64

In [29]:
df['weekday'] = df['datetime'].dt.weekday

In [30]:
df.weekday.value_counts()

5    3433
2    3431
4    3362
0    3349
3    3306
6    3287
1    3244
Name: weekday, dtype: int64

In [31]:
df['time'] = pd.to_datetime(df['Time'], format="%H:%M:%S")

ValueError: time data '1975-02-23T02:58:41.000Z' does not match format '%H:%M:%S' (match)

buni vscodedagi ishimda qilganman o'xshagan