In [3]:
import pandas as pd
import sqlite3 as sql

In [4]:
db = sql.connect('new.db')
cursor = db.cursor()

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/Electricity_Production_By_Source.csv")
df.head()

,Entity,Code,Year,Electricity from coal (TWh),Electricity from gas (TWh),Electricity from hydro (TWh),Electricity from other renewables (TWh),Electricity from solar (TWh),Electricity from oil (TWh),Electricity from wind (TWh),Electricity from nuclear (TWh)
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0,0.0,0.0,0.0

In [6]:
cols = ['country', 'code', 'year', 'coal', 'gas', 'hydro', 'renewable_other', 'solar', 'oil', 'wind', 'nuclear']
df.columns = cols
df.head()

,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0,0.0,0.0,0.0

In [7]:
df.to_sql('elect', db)

6241

In [8]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('elect',)]

In [9]:
cursor.execute("PRAGMA table_info(elect);")
cursor.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 0),
 (2, 'code', 'TEXT', 0, None, 0),
 (3, 'year', 'INTEGER', 0, None, 0),
 (4, 'coal', 'REAL', 0, None, 0),
 (5, 'gas', 'REAL', 0, None, 0),
 (6, 'hydro', 'REAL', 0, None, 0),
 (7, 'renewable_other', 'REAL', 0, None, 0),
 (8, 'solar', 'REAL', 0, None, 0),
 (9, 'oil', 'REAL', 0, None, 0),
 (10, 'wind', 'REAL', 0, None, 0),
 (11, 'nuclear', 'REAL', 0, None, 0)]

In [10]:
query = "SELECT * FROM elect WHERE country = 'Uzbekistan';"
pd.read_sql(query, db)

,index,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,5964,Uzbekistan,UZB,2000,11.602405,25.523451,5.817000,0.0,0.000000,1.380143,0.0,0.0
1,5965,Uzbekistan,UZB,2001,11.766320,25.884038,5.899000,0.0,0.000000,1.399642,0.0,0.0
2,5966,Uzbekistan,UZB,2002,12.214374,26.869686,6.124000,0.0,0.000000,1.452939,0.0,0.0
3,5967,Uzbekistan,UZB,2003,11.833513,26.031852,7.544000,0.0,0.000000,1.407634,0.0,0.0
4,5968,Uzbekistan,UZB,2004,11.595776,25.508869,8.920000,0.0,0.000000,1.379355,0.0,0.0
5,5969,Uzbekistan,UZB,2005,11.490919,25.278199,8.838000,0.0,0.000000,1.366882,0.0,0.0
6,5970,Uzbekistan,UZB,2006,11.827788,26.019258,4.653000,0.0,0.000000,1.406953,0.0,0.0
7,5971,Uzbekistan,UZB,2007,12.051665,26.511751,4.610000,0.0,0.000000,1.433584,0.0,0.0
8,5972,Uzbekistan,UZB,2008,10.774273,23.701692,4.443000,0.0,0.000000,1.281634,0.0,0.0
9,5973,Uzbekistan,UZB,2009,9.084625,28.017530,6.418000,0.0,0.000000,1.080645,0.0,0.0
10,5974,Uzbekistan,UZB,2010,9.792027,30.199200,8.110000,0.0,0.000000,1.164793,0.0,0.0
11,5975,Uzbekistan,UZB,2011,10.534094,32.487781,5.646000,0.0,0.000000,1.253064,0.0,0.0
12,5976,Uzbekistan,UZB,2012,10.365016,31.966333,6.586000,0.0,0.000000,1.232952,0.0,0.0
13,5977,Uzbekistan,UZB,2013,10.939346,33.737603,5.647000,0.0,0.001996,1.301270,0.0,0.0
14,5978,Uzbekistan,UZB,2014,11.112674,34.272157,6.014000,0.0,0.002046,1.321888,0.0,0.0
15,5979,Uzbekistan,UZB,2015,10.519789,35.780629,6.998000,0.0,0.002176,1.251363,0.0,0.0
16,5980,Uzbekistan,UZB,2016,10.783891,36.678911,7.254000,0.0,0.004643,1.282778,0.0,0.0
17,5981,Uzbekistan,UZB,2017,10.998707,37.409561,8.343000,0.0,0.006290,1.308332,0.0,0.0
18,5982,Uzbekistan,UZB,2018,11.853192,40.315893,5.838030,0.0,0.006827,1.409975,0.0,0.0
19,5983,Uzbekistan,UZB,2019,12.297660,41.827647,5.451373,0.0,0.006827,1.462846,0.0,0.0
20,5984,Uzbekistan,UZB,1985,NaN,NaN,5.431443,0.0,0.000000,NaN,0.0,0.0
21,5985,Uzbekistan,UZB,1986,NaN,NaN,4.618273,0.0,0.000000,NaN,0.0,0.0
22,5986,Uzbekistan,UZB,1987,NaN,NaN,6.770521,0.0,0.000000,NaN,0.0,0.0
23,5987,Uzbekistan,UZB,1988,NaN,NaN,7.163847,0.0,0.000000,NaN,0.0,0.0
24,5988,Uzbekistan,UZB,1989,NaN,NaN,5.502153,0.0,0.000000,NaN,0.0,0.0
25,5989,Uzbekistan,UZB,1990,NaN,NaN,6.648000,0.0,0.000000,NaN,0.0,0.0
26,5990,Uzbekistan,UZB,1991,NaN,NaN,6.031000,0.0,0.000000,NaN,0.0,0.0
27,5991,Uzbekistan,UZB,1992,NaN,NaN,6.281000,0.0,0.000000,NaN,0.0,0.0
28,5992,Uzbekistan,UZB,1993,NaN,NaN,7.358000,0.0,0.000000,NaN,0.0,0.0
29,5993,Uzbekistan,UZB,1994,NaN,NaN,7.156000,0.0,0.000000,NaN,0.0,0.0
30,5994,Uzbekistan,UZB,1995,NaN,NaN,6.188000,0.0,0.000000,NaN,0.0,0.0
31,5995,Uzbekistan,UZB,1996,NaN,NaN,6.525000,0.0,0.000000,NaN,0.0,0.0
32,5996,Uzbekistan,UZB,1997,NaN,NaN,5.777000,0.0,0.000000,NaN,0.0,0.0
33,5997,Uzbekistan,UZB,1998,NaN,NaN,5.758000,0.0,0.000000,NaN,0.0,0.0
34,5998,Uzbekistan,UZB,1999,NaN,NaN,5.692000,0.0,0.000000,NaN,0.0,0.0

In [11]:
query = """ 
CREATE TABLE IF NOT EXISTS worldpop(
rank INT,
country TEXT PRIMARY KEY,
density DOUBLE ,
population DOUBLE NOT NULL,
area INT NOT NULL
)
"""
cursor.execute(query)
db.commit()

In [12]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('elect',), ('worldpop',)]

In [13]:
cursor.execute("PRAGMA table_info(worldpop);")
cursor.fetchall()

[(0, 'rank', 'INT', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 1),
 (2, 'density', 'DOUBLE', 0, None, 0),
 (3, 'population', 'DOUBLE', 1, None, 0),
 (4, 'area', 'INT', 1, None, 0)]

In [14]:
query = "INSERT INTO worldpop VALUES(1, 'Macau',21946.25,658.256,30)"
cursor.execute(query)
db.commit()

In [15]:
cursor.execute("SELECT * FROM worldpop")
cursor.fetchall()

[(1, 'Macau', 21946.25, 658.256, 30)]

In [16]:
query = "INSERT INTO worldpop (country, population, area) VALUES ('Uzbekistan', 3354.86, 4561.456)"
cursor.execute(query)
db.commit()

In [17]:
cursor.execute("SELECT * FROM worldpop")
cursor.fetchall()

[(1, 'Macau', 21946.25, 658.256, 30),
 (None, 'Uzbekistan', None, 3354.86, 4561.456)]

In [18]:
pd.read_sql("SELECT * FROM worldpop", db)

   rank     country   density  population      area
0   1.0       Macau  21946.25     658.256    30.000
1   NaN  Uzbekistan       NaN    3354.860  4561.456

In [21]:
query = "UPDATE worldpop SET rank=133, density= 75.811 WHERE country = 'Uzbekistan'"
cursor.execute(query)
db.commit()

In [22]:
pd.read_sql("SELECT * FROM worldpop", db)

   rank     country    density  population      area
0     1       Macau  21946.250     658.256    30.000
1   133  Uzbekistan     75.811    3354.860  4561.456

In [23]:
query = "DELETE FROM worldpop WHERE country = 'Macau'"
cursor.execute(query)
db.commit()

In [24]:
pd.read_sql("select * from worldpop", db)

   rank     country  density  population      area
0   133  Uzbekistan   75.811     3354.86  4561.456

In [25]:
cursor.execute("Drop table worldpop")
db.commit()

In [26]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/world_population.csv", index_col='rank')
df.head()

        country     density   densityMi   pop2021  area
rank
1         Macau  21946.4667  56841.3487   658.394    30
2        Monaco  19755.5000  51166.7450    39.511     2
3     Singapore   8305.1915  21510.4461  5896.686   710
4     Hong Kong   6841.3134  17719.0017  7552.810  1104
5     Gibraltar   5616.3333  14546.3033    33.698     6

In [27]:
query = """
CREATE TABLE IF NOT EXISTS worldpop(
rank INT,
country TEXT PRIMARY KEY,
density DOUBLE,
population DOUBLE NOT NULL,
area INT NOT NULL
);
"""

cursor.execute(query)
db.commit()

In [28]:
uz = df[df.country == 'Uzbekistan']
uz

         country  density  densityMi    pop2021    area
rank
133   Uzbekistan  75.8511   196.4542  33935.763  447400

In [29]:
rank = uz.index.values[0]
country = uz.at[rank, 'country']
density = uz.at[rank, 'density']
population = uz.at[rank, 'pop2021']
area = uz.at[rank, 'area']
print(f"{rank}, {country}, {density}, {population}, {area}")

133, Uzbekistan, 75.8511, 33935.763, 447400

In [30]:
query = f"""
INSERT INTO worldpop VALUES ({rank}, '{country}', {density}, {population}, {area})
"""

cursor.execute(query)
db.commit()

In [31]:
cursor.execute("SELECT * FROM worldpop")
cursor.fetchall()

[(133, 'Uzbekistan', 75.8511, 33935.763, 447400)]

In [32]:
db.close()