In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
!wget "https://github.com/anvarnarz/praktikum_datasets/raw/main/electricity.db"

--2026-04-10 11:37:17--  https://github.com/anvarnarz/praktikum_datasets/raw/main/electricity.db
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/electricity.db [following]
--2026-04-10 11:37:18--  https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/electricity.db
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 565248 (552K) [application/octet-stream]
Saving to: ‘electricity.db’

electricity.db      100%[===================>] 552.00K   412KB/s    in 1.3s

2026-04-10 11:37:21 (412 KB/s) - ‘electricity.db’ saved [565248/565248]

In [3]:
db = sql.connect('electricity.db')
cursor = db.cursor()

In [4]:
cursor.execute("SELECT name FROM sqlite_master WHERE type = 'table';")
print(cursor.fetchall())

[('elect',)]

In [6]:
cursor.execute("PRAGMA table_info(elect)")
cursor.fetchall()

[(0, 'index', 'INTEGER', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 0),
 (2, 'code', 'TEXT', 0, None, 0),
 (3, 'year', 'INTEGER', 0, None, 0),
 (4, 'coal', 'REAL', 0, None, 0),
 (5, 'gas', 'REAL', 0, None, 0),
 (6, 'hydro', 'REAL', 0, None, 0),
 (7, 'renewable_other', 'REAL', 0, None, 0),
 (8, 'solar', 'REAL', 0, None, 0),
 (9, 'oil', 'REAL', 0, None, 0),
 (10, 'wind', 'REAL', 0, None, 0),
 (11, 'nuclear', 'REAL', 0, None, 0)]

In [7]:
pd.read_sql("SELECT * FROM elect LIMIT 15", db, index_col='index')

,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
index,,,,,,,,,,,
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0000,0.0,0.00000,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0000,0.0,0.00000,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0000,0.0,0.00000,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0000,0.0,0.00000,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0000,0.0,0.00000,0.0
5,Afghanistan,AFG,2005,0.0,0.344,0.590,0.0,0.0000,0.0,0.00000,0.0
6,Afghanistan,AFG,2006,0.0,0.200,0.637,0.0,0.0000,0.0,0.00000,0.0
7,Afghanistan,AFG,2007,0.0,0.198,0.748,0.0,0.0000,0.0,0.00000,0.0
8,Afghanistan,AFG,2008,0.0,0.186,0.542,0.0,0.0000,0.0,0.00001,0.0
9,Afghanistan,AFG,2009,0.0,0.162,0.776,0.0,0.0000,0.0,0.00010,0.0
10,Afghanistan,AFG,2010,0.0,0.185,0.751,0.0,0.0002,0.0,0.00010,0.0
11,Afghanistan,AFG,2011,0.0,0.252,0.595,0.0,0.0002,0.0,0.00010,0.0
12,Afghanistan,AFG,2012,0.0,0.174,0.710,0.0,0.0280,0.0,0.00000,0.0
13,Afghanistan,AFG,2013,0.0,0.218,0.855,0.0,0.0300,0.0,0.00000,0.0
14,Afghanistan,AFG,2014,0.0,0.154,0.968,0.0,0.0320,0.0,0.00000,0.0

In [13]:
query = "SELECT DISTINCT country FROM elect"
countries = pd.read_sql(query,db)
countries

            country
0       Afghanistan
1            Africa
2           Albania
3           Algeria
4    American Samoa
..              ...
230  Western Sahara
231           World
232           Yemen
233          Zambia
234        Zimbabwe

[235 rows x 1 columns]

In [14]:
'Uzbekistan' in countries['country'].values

True

In [19]:
query = "SELECT * FROM elect WHERE country ='Uzbekistan' AND year > 2010"
dfuz = pd.read_sql(query, db)
dfuz

,index,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,5975,Uzbekistan,UZB,2011,10.534094,32.487781,5.646000,0.0,0.000000,1.253064,0.0,0.0
1,5976,Uzbekistan,UZB,2012,10.365016,31.966333,6.586000,0.0,0.000000,1.232952,0.0,0.0
2,5977,Uzbekistan,UZB,2013,10.939346,33.737603,5.647000,0.0,0.001996,1.301270,0.0,0.0
3,5978,Uzbekistan,UZB,2014,11.112674,34.272157,6.014000,0.0,0.002046,1.321888,0.0,0.0
4,5979,Uzbekistan,UZB,2015,10.519789,35.780629,6.998000,0.0,0.002176,1.251363,0.0,0.0
5,5980,Uzbekistan,UZB,2016,10.783891,36.678911,7.254000,0.0,0.004643,1.282778,0.0,0.0
6,5981,Uzbekistan,UZB,2017,10.998707,37.409561,8.343000,0.0,0.006290,1.308332,0.0,0.0
7,5982,Uzbekistan,UZB,2018,11.853192,40.315893,5.838030,0.0,0.006827,1.409975,0.0,0.0
8,5983,Uzbekistan,UZB,2019,12.297660,41.827647,5.451373,0.0,0.006827,1.462846,0.0,0.0

In [20]:
query = "SELECT country,year, coal,gas, hydro, oil FROM elect WHERE country ='Uzbekistan' AND year BETWEEN 2010 AND 2015"
pd.read_sql(query,db)

      country  year       coal        gas  hydro       oil
0  Uzbekistan  2010   9.792027  30.199200  8.110  1.164793
1  Uzbekistan  2011  10.534094  32.487781  5.646  1.253064
2  Uzbekistan  2012  10.365016  31.966333  6.586  1.232952
3  Uzbekistan  2013  10.939346  33.737603  5.647  1.301270
4  Uzbekistan  2014  11.112674  34.272157  6.014  1.321888
5  Uzbekistan  2015  10.519789  35.780629  6.998  1.251363

In [21]:
query = "SELECT country,year, coal,gas, hydro, oil FROM elect WHERE country ='Uzbekistan' AND year IN (2005,2008, 2009,2015)"
pd.read_sql(query,db)

      country  year       coal        gas  hydro       oil
0  Uzbekistan  2005  11.490919  25.278199  8.838  1.366882
1  Uzbekistan  2008  10.774273  23.701692  4.443  1.281634
2  Uzbekistan  2009   9.084625  28.017530  6.418  1.080645
3  Uzbekistan  2015  10.519789  35.780629  6.998  1.251363

In [22]:
# LIKE operatori uchun namunalar:
# %var   -> Anvar, Sarvar (oxiri 'var' bilan tugaydigan har qanday so'z)
# _ar    -> car, bar, tar (bitta ixtiyoriy belgi + 'ar')
# __ar   -> star (ikkita ixtiyoriy belgi + 'ar')
# %ol%   -> bola, xola, bolalar ('ol' birikmasi so'zning istalgan joyida bor bo'lsa)

query = "SELECT * FROM elect WHERE country LIKE '%stan' AND year IN (2019, 2020, 2021)"
pd.read_sql(query, db)

,index,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,19,Afghanistan,AFG,2019,0.000000,0.152000,0.840000,0.000000,0.040000,0.000000,0.000000,0.000000
1,2847,Kazakhstan,KAZ,2019,71.206910,18.960820,9.842580,0.001000,0.236000,0.755650,0.549000,0.000000
2,2848,Kazakhstan,KAZ,2020,72.193448,19.223513,9.403480,0.002900,1.077300,0.755650,0.941200,0.000000
3,2963,Kyrgyzstan,KGZ,2019,1.056225,0.000000,13.705560,0.000000,0.000000,0.078355,0.000000,0.000000
4,4303,Pakistan,PAK,2019,24.827532,24.776677,43.146492,2.659467,1.031600,35.551972,3.608753,9.783445
5,4304,Pakistan,PAK,2020,29.319484,17.517486,47.296196,2.675689,1.030267,34.513517,3.190669,9.909005
6,5495,Tajikistan,TJK,2019,0.000000,0.000000,18.977310,0.000000,0.000000,1.416580,0.000000,0.000000
7,5496,Tajikistan,TJK,2020,0.000000,0.000000,18.489310,0.000000,0.000000,1.416580,0.000000,0.000000
8,5704,Turkmenistan,TKM,2019,0.000000,7.230340,0.000300,0.000000,0.000000,13.951674,0.000000,0.000000
9,5983,Uzbekistan,UZB,2019,12.297660,41.827647,5.451373,0.000000,0.006827,1.462846,0.000000,0.000000

In [23]:
query = "SELECT * FROM elect WHERE code LIKE 'A__' AND year=2020"
pd.read_sql(query, db)

,index,country,code,year,coal,gas,hydro,renewable_other,solar,oil,wind,nuclear
0,225,Argentina,ARG,2020,1.445719,86.689660,20.853642,1.893496,1.344267,3.492022,9.419758,10.010408
1,336,Australia,AUS,2020,135.099330,48.132519,16.112890,3.443160,18.638820,5.612541,24.308719,0.000000
2,357,Austria,AUT,2020,0.716660,10.440827,42.883119,4.068629,1.264996,3.249908,6.868170,0.000000
3,393,Azerbaijan,AZE,2020,0.000000,12.514432,1.549350,0.155333,0.044000,11.379848,0.135000,0.000000